### ISSUE TITLE
Punctuation removal in Athena/prepare_data.py fuses words in transcripts added to .csv files

### ISSUE THREAD

**Issue by IanMGriff** [SpeechColab/GigaSpeech#103]
Potential bug fix in the Athena toolkit prepare data script:

starting on 135 of `prepare_data.py`,  this section  strips punctation without adding a space, then *removes* double spaces:
```
transcriptions = re.sub(punctuation_tags, "", transcriptions)
# convert two spaces to one space
transcriptions = re.sub("  ", "", transcriptions)
```

This first line should be fine as most punctuation is followed by a space. However, because transcripts in the `text` file are already space separated, the second line is stripping without replacing, resulting in the neighboring words getting fused together. 

I.e. this sentence:
```DOUGLAS MCGRAY IS GOING TO BE OUR GUIDE YOU WALK THROUGH THE DOOR <COMMA> YOU SEE THE RED CARPETING <COMMA> YOU SEE SOMEONE IN A SUIT <PERIOD> THEY MAY BE GREETING YOU <PERIOD>```

Becomes:
```DOUGLAS MCGRAY IS GOING TO BE OUR GUIDE YOU WALK THROUGH THE DOORYOU SEE THE RED CARPETINGYOU SEE SOMEONE IN A SUITTHEY MAY BE GREETING YOU``` 

Simply changing 
```
transcriptions = re.sub("  ", "", transcriptions)
```
to 
```
transcriptions = re.sub("  ", " ", transcriptions)
``` 
may fix the issue

**Comment by dophist** [comment]
I'm not sure if the maintainer of those scripts is watching this repo. The fix seems pretty solid, good catch.  Do you mind submitting a PR, I can merge it right away.

**Comment by dophist** [comment]
Fixed in PR https://github.com/SpeechColab/GigaSpeech/pull/123 , closing
