### ISSUE TITLE
Model size and training time on the leaderboard

### ISSUE THREAD

**Issue by csukuangfj** [SpeechColab/GigaSpeech#111]
It is unfair to compare the WERs without mentioning the number of model parameters.

Would be great if the model size, training time per epoch, and the number of trained epochs are also listed on the leaderboard.

**Comment by chenguoguo** [comment]
Thanks. We are hoping that people will provide such information under `Train Recipe` (links to detailed descriptions), but you are welcome to submit a PR for that.
