### ISSUE TITLE
reorg utils/analyze_meta.py

### ISSUE THREAD

**Issue by dophist** [SpeechColab/GigaSpeech#12]
`utils/analyze_meta.py` seems to be a kaldi-specific tool, we should reorganize it into `toolkits/kaldi/`, and possibly rename it to something like `extract_kaldi_data_info.py`

**Comment by dophist** [comment]
@wangyongqing0731 any idea on how to reorganize this script?

**Comment by wangyongqing0731** [comment]
ok, i will reorganize analyze_meta.py into the specialized tools for kaldi

**Comment by dophist** [comment]
Done in https://github.com/SpeechColab/GigaSpeech/pull/21 , closing
