### ISSUE TITLE
Gigaspeech egs in Kaldi stopped 

### ISSUE THREAD

**Issue by leo1980** [SpeechColab/GigaSpeech#120]
When I train Gigaspeech in kaldi/egs/gigaspeech. It stopped during extracting feat as shown below, how can I solve it?
....
======Extract feat START | current time : 2022-09-08-23:36:51==========
steps/make_mfcc.sh --cmd run.pl --nj 30 data/gigaspeech_dev exp/make_mfcc/gigaspeech_dev mfcc
steps/make_mfcc.sh: moving data/gigaspeech_dev/feats.scp to data/gigaspeech_dev/.backup
utils/validate_data_dir.sh: Successfully validated data-directory data/gigaspeech_dev
steps/make_mfcc.sh [info]: segments file exists: using that.
steps/make_mfcc.sh: Succeeded creating MFCC features for gigaspeech_dev
steps/compute_cmvn_stats.sh data/gigaspeech_dev exp/make_mfcc/gigaspeech_dev mfcc
Succeeded creating CMVN stats for gigaspeech_dev
steps/make_mfcc.sh --cmd run.pl --nj 30 data/gigaspeech_test exp/make_mfcc/gigaspeech_test mfcc
steps/make_mfcc.sh: moving data/gigaspeech_test/feats.scp to data/gigaspeech_test/.backup
utils/validate_data_dir.sh: **Error**: in data/gigaspeech_test, speaker lists extracted from spk2utt and cmvn
utils/validate_data_dir.sh: differ, partial diff is:
--- /tmp/kaldi.LRoo/speakers	2022-09-08 23:37:28.100356559 +0800
+++ /tmp/kaldi.LRoo/speakers.cmvn	2022-09-08 23:37:28.096356455 +0800
@@ -12301,3 +12301,2 @@
 YOU1000000101_S0000152
-YOU1000000101_S0000153
 YOU1000000101_S0000154
...
 YOU1000000192_S0000233
-YOU1000000192_S0000234
 YOU1000000192_S0000235
@@ -25618,2 +25376 @@
 YOU1000000192_S0000247
-YOU1000000192_S0000248
[Lengths are /tmp/kaldi.LRoo/speakers=25619 versus /tmp/kaldi.LRoo/speakers.cmvn=25376]

**Comment by chenguoguo** [comment]
Could you check if your feature extraction failed for certain IDs (see the diff)

**Comment by leo1980** [comment]
I looked into utils/validate_data_dir.sh, found the code which generated the error shown above,
```
286 if [ -f $data/cmvn.scp ]; then
287   check_sorted_and_uniq $data/cmvn.scp
288   cat $data/cmvn.scp | awk '{print $1}' > $tmpdir/speakers.cmvn
289   cat $data/spk2utt | awk '{print $1}' > $tmpdir/speakers
290   if ! cmp -s $tmpdir/speakers{,.cmvn}; then
291     echo "$0: Error: in $data, speaker lists extracted from spk2utt and cmvn"
```
It compares first column of these 2 files 
data/gigaspeech_test/cmvn.scp  
data/gigaspeech_test/spk2utt

I used command vimdiff to compare 2 files
$> vimdiff data/gigaspeech_test/cmvn.scp data/gigaspeech_test/spk2utt
found the first difference is as shown below - there is a id jump in cmvn.scp, from YOU1000000101_S0000152 to YOU1000000101_S0000154, which supposed to be YOU1000000101_S0000153, I think. 

<pre><font color="#FCE94F">12301 </font><span style="background-color:#75507B">YOU1000000101_S0000152 </span><span style="background-color:#EF2929"><b>/home/xxx/storage/original_storage_folder/kaldi/egs/gigaspeech/s5/mfcc</b></span><span style="background-color:#FFFFFF"><font color="#300A24"> </font></span><span style="background-color:#6C6C6C"><font color="#34E2E2">  </font></span><font color="#FCE94F">12301 </font><span style="background-color:#75507B">YOU1000000101_S0000152 </span><span style="background-color:#EF2929"><b>YOU1000000101_S0000152</b></span><span style="background-color:#75507B">                                                </span>
<span style="background-color:#6C6C6C"><font color="#34E2E2"></font></span><font color="#FCE94F">12302 </font><span style="background-color:#75507B">YOU1000000101_S000015</span><span style="background-color:#EF2929"><b>4 /home/xxx/storage/original_storage_folder/kaldi/egs/gigaspeech/s5/mfcc</b></span><span style="background-color:#FFFFFF"><font color="#300A24"> </font></span><span style="background-color:#6C6C6C"><font color="#34E2E2">  </font></span><font color="#FCE94F">12302 </font><span style="background-color:#75507B">YOU1000000101_S000015</span><span style="background-color:#EF2929"><b>3 YOU1000000101_S0000153</b></span><span style="background-color:#75507B">        </span></pre>

**Comment by chenguoguo** [comment]
That means it failed to extract mfcc/cmvn for `YOU1000000101_S0000153`. You can check the logs and see what happens. Or you can modify your file to skip it.

**Comment by leo1980** [comment]
I checked log
exp/make_mfcc/gigaspeech_test/cmvn_gigaspeech_test.log
It complains 
<pre><font color="#FCE94F"> 2 </font>WARNING (compute-cmvn-stats[5.5.1038~1-9af2c]:main():compute-cmvn-stats.cc:107) Did not find features for utterance YOU1000000101_S0000153
<font color="#FCE94F">  3 </font>WARNING (compute-cmvn-stats[5.5.1038~1-9af2c]:main():compute-cmvn-stats.cc:123) No stats accumulated for speaker YOU1000000101_S0000153
</pre>
Then I check feature file
mfcc/cmvn_gigaspeech_test.scp

found YOU1000000101_S0000153 is not there, then check feature extraction log
exp/make_mfcc/gigaspeech_test/make_mfcc_gigaspeech_test.15.log

found that YOU1000000101_S0000153 is skipped because it is too short
WARNING (extract-segments[5.5.1038~1-9af2c]:main():extract-segments.cc:158) Segment YOU1000000101_S0000153 too short, skipping it.

Should we change utils/validate_data_dir.sh to fix this? like remove those utterances that are missing in feature scp file?

**Comment by chenguoguo** [comment]
I wouldn't touch the validation script. Instead, you should remove these lines manually or try to figure out why you didn't get features for these lines.

**Comment by dophist** [comment]
@leo1980 imho, this question is really not supposed to be asked here. 

This repo is all about the `dataset` itself, whereas the question you are diving into is essentially a `recipe` thing, which are supposed to be maintained by various toolkits owners.  So the maintainers of this repo are not guaranteed to help you out with very specific advices, unless you track the problem down and find out there's indeed an upstream dataset error, which I think is probably not the case. 

I'm not sure if you can get quick responses from Kaldi community, the next-gen Kaldi community should be much more active.

One fact that might be helpful to you, is that all training utterances in GigaSpeech are guaranteed to have a duration >= 0.5 sec. If this is not the case for your local copy, this repo contains strict MD5 checking tool(in `utils/`) to help you with the consistency validation.  And it's always worth it to make sure your local data is consistent with the release before any large-scale/serious experiments and trainings, particularly for large dataset like GigaSpeech.
