### ISSUE TITLE
bug when we use subset_data_dir.sh in  gigaspeech_data_prep.sh

### ISSUE THREAD

**Issue by sw005320** [SpeechColab/GigaSpeech#16]
I got the following error:
```
$ ./toolkits/kaldi/gigaspeech_data_prep.sh ${GIGASPEECH} /expscratch/swatanabe/202007espnet/espnet_v2/egs2/gigaspeech/asr1/tmp true
/expscratch/swatanabe/202007espnet/espnet_v2/egs2/gigaspeech/asr1/utils/subset_data_dir.sh: line 101: utils/filter_scp.pl: No such file or directory
```
`subset_data_dir.sh` requires `utils/filter_scp.pl` but cannot find it.
This is because `gigaspeech_data_prep.sh` is designed to be executed at GigaSpeech while these Kaldi scripts are designed to be executed at `kaldi/egs/***/s5/` where we have a symlink to point out `utils/filter_scp.pl`

Please fix it.

**Comment by dophist** [comment]
Shinji, @wangyongqing0731 is working on Kaldi recipe, I remember a snippet of his raft is calling GigaSpeech_git_repo/toolkits/kaldi/xxx under kaldi_root/egs/gigaspeech/s5, we can keep track and adress this issue when his recipe raft is out.

**Comment by chenguoguo** [comment]
I was trying to make all GigaSpeech scripts relative to the GigaSpeech repo
and that introduced the issue. I’ll try to figure out what is the best way
to do this.

**Comment by sw005320** [comment]
I think we could copy the necessary scripts from Kaldi. 
We may also care `utt2spk_to_spk2utt.pl` https://github.com/SpeechColab/GigaSpeech/blob/main/toolkits/kaldi/gigaspeech_data_prep.sh#L60, as well, but baically that's it.

**Comment by chenguoguo** [comment]
Yeah let me think about it. Ideally I'd like to avoid copying scripts from
Kaldi so that it's easier to maintain. But I guess it's fine if we have to.

Guoguo

**Comment by naxingyu** [comment]
What if adding a `path.sh` or `env.sh` to export `$KALDI_ROOT/egs/wsj/s5/utils` ?

**Comment by dophist** [comment]
As a reminder, GigaSpeech Kaldi recipe draft from @wangyongqing0731 is out here, we can review. https://github.com/SpeechColab/kaldi/pull/1/files.

1. For Kaldi recipe, I think It is OK that we assume PWD is $KALDI_ROOT/egs/xxx/s5/, and avoid copying kaldi script into GigaSpeech repo
2. For Espnet1 recipe(with kaldi dependency), it's better to follow espnet1's way to locate Kaldi, and copy kaldi scripts into GigaSpeech/toolkits/espnet1/ only when it is necessary.
3. For Espnet2 recipe, we can implement necessary utilities that are specific to espnet2's requirements in GigaSpeech/toolkits/espnet2/

**Comment by wangyongqing0731** [comment]
> What if adding a `path.sh` or `env.sh` to export `$KALDI_ROOT/egs/wsj/s5/utils` ?

@naxingyu It doesn't work, because there's some relative path in subset_data_dir.sh, eg. utils/filter_scp.pl and so on.
Unless,  remove all relative path in kaldi script, which are used in gigaspeech
