### ISSUE TITLE
need some more cleaning of the data?

### ISSUE THREAD

**Issue by sw005320** [SpeechColab/GigaSpeech#17]
This is just FYI.

I found a lot of CTC warnings in espnet (I observed more than 100 utterances now, but it seem to be even more. I'll let you know the exact numbers later).
```
WARNING: The grad norm is nan. Skipping updating the model.
```
This happens when the output length is longer than the (subsampled) input length.
Normal speech utterances do not have this situation since people cannot speak so fast, and I think it should be due to some errors in the transcriptions, alignments, or broken audio files.
For now, I just added an option to skip such utterances during training.
Also, it would be relatively small compared with the entire utterances, and the effect would be small.

However, this kind of data can be easily detected by checking the input and output lengths.
We may exclude them in advance.

**Comment by chenguoguo** [comment]
Great, keep us posted if you have a full list. Will check in details.

**Comment by dophist** [comment]
will have a specific check on this issue, thanks, Shinji.

**Comment by dophist** [comment]
sorting entire dataset by "number_of_chars/sec of an utterance" (first column above), giving the above list. 
```
79.48717948718227 YOU0000005203_S0000151 0.7799999999999727 YOU KNOW WHAT I MEAN <QUESTIONMARK>     YEAH <COMMA> YEAH <PERIOD>
79.60199004975385 POD1000000043_S0000023 0.2009999999999934 OH YEAH <PERIOD>
79.99999999999835 POD1000000046_S0000051 0.2750000000000057 YEP <EXCLAMATIONPOINT>
80.13937282229 POD1000000040_S0000135 0.28700000000003456 YEAH <EXCLAMATIONPOINT>
80.13937282229 POD1000000040_S0000230 0.28700000000003456 YEAH <EXCLAMATIONPOINT>
80.13937282229 POD1000000046_S0000362 0.28700000000003456 YEAH <EXCLAMATIONPOINT>
80.70175438595783 YOU0000014891_S0000191 0.57000000000005 CIAO <EXCLAMATIONPOINT> BYE               <EXCLAMATIONPOINT>
83.63636363633597 POD1000000046_S0000726 0.27500000000009095 YEAH <EXCLAMATIONPOINT>
83.6363636363619 POD1000000046_S0000070 0.2750000000000057 YEAH <EXCLAMATIONPOINT>
84.44444444439324 POD1000000012_S0000292 0.22500000000013642 WHAT <QUESTIONMARK>
84.84848484848528 YOU0000001008_S0000060 0.6599999999999966 SO EVERYTHING <EXCLAMATIONPOINT> YEAH   <EXCLAMATIONPOINT>
86.46616541358291 POD1000000046_S0000584 0.265999999999849 YEAH <EXCLAMATIONPOINT>
86.95652173910923 POD1000000011_S0000066 0.13800000000003365 YEP <PERIOD>
87.78625954200362 POD1000000046_S0000381 0.2619999999999436 YEAH <EXCLAMATIONPOINT>
89.4736842105363 YOU0000000109_S0000401 0.5699999999999363 UM MARCO <EXCLAMATIONPOINT> POLO         <EXCLAMATIONPOINT>
93.33333333337106 POD1000000046_S0000904 0.22499999999990905 AH <EXCLAMATIONPOINT>
100.84033613447806 POD1000000040_S0000173 0.2379999999999427 RIGHT <EXCLAMATIONPOINT>
106.55737704918126 YOU0000011422_S0000090 1.829999999999984 BUT FUCK <EXCLAMATIONPOINT> FUCK        <EXCLAMATIONPOINT> FUCK <EXCLAMATIONPOINT> FUCK <EXCLAMATIONPOINT> FUCK <EXCLAMATIONPOINT> FUCK     <EXCLAMATIONPOINT> FUCK <EXCLAMATIONPOINT> FUCK <EXCLAMATIONPOINT>
184.0 POD1000000046_S0000224 0.125 YEAH <EXCLAMATIONPOINT>
243.6472346786311 POD1000000043_S0000050 1.3379999999999654 BUT THEN THERE IS THIS TEAM AH AH       ADMINISTRATION OFFICIAL AND THE PEACE <COMMA> AND THEY ARE QUOTED TO SAYING SOMETHING ALONG THE     LINES OF <COMMA> IN TWENTY YEARS PEOPLE WON'T REMEMBER BLEACH <COMMA> THEY WON'T REMEMBER HIM NOT   WEARING MASKS THEY WON'T REMEMBER THIS <COMMA> THEY'LL JUST REMEMBER OPERATION WARP SPEED <PERIOD>
335.76642335766314 POD1000000026_S0000036 0.13700000000000045 THAT'S WHAT I SAID <COMMA> VERY BASIC <PERIOD>
```
From what I see, two points needs attention:
1. punctuations: we have 4 punctuations supported in our corpus, they are 
```
<COMMA>
<PERIOD>
<QUESTIONMARK>
<EXCLAMATIONPOINT>
```
@sw005320 , treating these tags as normal characters might be a source of the problem. @chenguoguo we should put punctuations related info to somewhere that users can easily see, maybe repo README ?

2. The most problematic two utterances in the bottom are from test sets(by human annotators), content & timestamp doesn't match up at all. It must be accidental mis-operations of our human annotators.  we should add a round of model-based validation to human-annotated test/dev sets, to enhance labelling quality.

**Comment by sw005320** [comment]
Thanks for the investigation!
These punctuations are removed in the data preparation. 
So, they should be no problem.

**Comment by chenguoguo** [comment]
Shinji will you be able to post the segment id for those problematic
utterances? I’d like to take a closer look at this.

**Comment by sw005320** [comment]
After I fix some correct CTC use, I found that there are only two utterances in the entire training data.
(and sorry that our current program does not record the utterance ID...)
So, I think we can ignore this issue.

Sorry to take your time, but we don't have to care so much about this issue.
I'll close the issue.
