### ISSUE TITLE
download without  aliyun_ossutil.cfg 

### ISSUE THREAD

**Issue by mahuichao** [SpeechColab/GigaSpeech#20]
hello ,I don't know what is aliyun_ossutil.cfg ,I don't have it . If I want to download data,what could I do?

**Comment by dophist** [comment]
you need to wait a couple of weeks, currently GigaSpeech dataset is only available for our close collaborators.

**Comment by mahuichao** [comment]
OK ,Thanks for replying.

**Comment by double22a** [comment]
waiting for you

**Comment by Mddct** [comment]
Any progress for this？

**Comment by dophist** [comment]
We are working on sustainable ways to distribute GigaSpeech dataset, need more time.

Shouldn't be long though, I'll push notices to this repo as soon as distribution channel is ready.
