### ISSUE TITLE
403 error when downloading dataset

### ISSUE THREAD

**Issue by m-learner-1** [SpeechColab/GigaSpeech#42]
I get this error when I try to download the dataset:
```
Error: oss: service returned error: StatusCode=403, ErrorCode=, ErrorMessage="", RequestId=..., Bucket=speechcolab, Object=GigaSpeech/release/GigaSpeech/GigaSpeech.json
```

In case its useful, the region is Hangzhou and I get a longer "Access Denied" message when I run ls on the oss path:
```
ossutil64 -c SAFEBOX/aliyun_ossutil.cfg ls oss://speechcolab/GigaSpeech/release/GigaSpeech/GigaSpeech.json
Error: oss: service returned error: StatusCode=403, ErrorCode=AccessDenied, ErrorMessage="The bucket you access does not belong to you.", RequestId=..., Bucket=speechcolab, Object=
```

**Comment by SpeechColab** [comment]
Hi, we are in the middle of moving the data to difficult hosts and we are
going to officially release the data in a few weeks. I hope it’s not
too late for you?

**Comment by lahiruts** [comment]
Hi, could you please let us know the timeline for the official release? Thanks.

**Comment by xforceco** [comment]
Can you please let us know the "GIGA_SPEECH_RELEASE_URL"  for downloading?
Thank you

**Comment by chenguoguo** [comment]
We moved the data to new hosts, and we will publish this by the end of June, which is, in a couple of days :-)

**Comment by benjaminwar** [comment]
Is today the day :) ?

**Comment by chenguoguo** [comment]
5 days passed the deadline... but please check out the Download section of the README file now :-)

**Comment by dophist** [comment]
GigaSpeech is released, you can find download instructions in repo readme, closing.
