### ISSUE TITLE
aliyun_ossutil.cfg 

### ISSUE THREAD

**Issue by lilimor** [SpeechColab/GigaSpeech#44]
is it possible to get access to this file aliyun_ossutil.cfg

where can I found it ?

thanks

**Comment by chenguoguo** [comment]
Hey we moved from oss to the Tsinghua University host. Please checkout the Download section of the README file. Sorry it took us a while to finish all these...

**Comment by dophist** [comment]
GigaSpeech is released, see repo readme for detail instructions.  Closing this.
