### ISSUE TITLE
Question: Hosting files on HuggingFace Hub?

### ISSUE THREAD

**Issue by alexsounder** [SpeechColab/GigaSpeech#48]
Will you consider hosting GigaSpeech on HuggingFace hub? The awesome HF team made dataset handling very fast and easy.

**Comment by dophist** [comment]
Thanks for the advice. I investigated a little on that, it seems that GigaSpeech is two orders of magnitude larger than typical datasets hosted on hugging face, I'm not sure they are willing to help us host and distribute such large dataset.
