### ISSUE TITLE
Problems regarding to dataset downloading

### ISSUE THREAD

**Issue by dophist** [SpeechColab/GigaSpeech#60]
* It's challenging to distribute giant datasets like GigaSpeech without resorting to robust commercial cloud services.  It was roughly estimated that a single downloading of GigaSpeech will incur fees around 200 USD( from Amazon S3) and around 1000 CNY(from Aliyun OSS).
* We don't want our users to pay such expensive fees and we are currently a non-profit group of volunteers, so the dataset distribution is hosted via Tsinghua University, and it is expected that the downloading channel may be crowded in early days of GigaSpeech release.
* You can always rerun our downloading script to resume interrupted or incomplete downloading sessions, as long as the destination directory doesn't change.
* In the last stage of our downloading script, there is a full-sweep of md5 check over downloaded resources, this should be the ultimate confirmation that you get everything right and intact.  If this stage fails, please rerun downloading script.
* We hope our users can understand this and we are open to any possible complaints and suggestions to help us improve
* Please report issues regarding to dataset downloading under this thread and this could be a time-saver for all future GigaSpeech users.

Best regards.

**Comment by snakers4** [comment]
You consider torrents. If people will behave (which they never do, because you know, Internet), the burden can be relieved 10-20x after you get 5-10 seeders.

Some examples:

- https://academictorrents.com/details/cc9dc56afd3055c7e0f021ec4f1824021558926c
- https://academictorrents.com/details/95b4cab0f99850e119114c8b6df00193ab5fa34f
- https://github.com/snakers4/open_stt/#via-torrent

**Comment by dophist** [comment]
> You can consider torrents. If people will behave (which they never do, because you know, Internet), the burden can be relieved 10-20x after you get 5-10 seeders.
> 
> Some examples:
> 
> * https://academictorrents.com/details/cc9dc56afd3055c7e0f021ec4f1824021558926c
> * https://academictorrents.com/details/95b4cab0f99850e119114c8b6df00193ab5fa34f
> * https://github.com/snakers4/open_stt/#via-torrent

Thank you Alex, will try.

**Comment by chenguoguo** [comment]
Hopefully things will get better after the first few days. But we'll also try to add more hosts.

**Comment by snakers4** [comment]
By the way, looks like the download hangs now:

![image](https://user-images.githubusercontent.com/12515440/124877428-bbfdd480-dfd3-11eb-8c8b-a8c40eebd5c4.png)

**Comment by chenguoguo** [comment]
There are too many people downloading at the same time... we are exploring a few ways, including adding new hosts. Will update here.

**Comment by ahazned** [comment]
I really do appreciate your efforts on collecting and sharing such a great dataset, thank you very very much for this. 

But unfortunately it is almost impossible to download the dataset right now.

**Comment by chenguoguo** [comment]
Still working on it... Please allow us some time.

**Comment by robmsmt** [comment]
+1 for torrents... Downloading at 4.30KB/s

**Comment by chenguoguo** [comment]
Added one host, and another is on the way. If you re-run your download script, it should be able to figure out the best download host: https://github.com/SpeechColab/GigaSpeech/pull/71

**Comment by dophist** [comment]
@chenguoguo Just added a new fast host, anyone can: 

1. stop your current downloading 
2. pull this repo
3. re-run downloading script

The new script should be able to resume your previous download(with much better speed), and repair any detected corrupted/out-dated files on your local disk.

**Comment by RuslanSel** [comment]
Can you please create separate download for test set? Cause it is impossible to download full dataset right now.

**Comment by chenguoguo** [comment]
@RuslanSel We will add the download for test set only. But why is it impossible to download the full dataset right now? If you pull the latest repo, you should be able to download the dataset in one day or so. Let us know if you are observing something else.

**Comment by RuslanSel** [comment]
My current speed is less than 100KB/s.

**Comment by SpeechColab** [comment]
Which host is this? Are you using the latest download code?

**Comment by RuslanSel** [comment]
https://freedata.oss-cn-beijing.aliyuncs.com
The latest download code.

**Comment by dophist** [comment]
Traffic rush is over, the GigaSpeech dataset downloading has been smooth for quite a while, closing.
