### ISSUE TITLE
Separate test set download

### ISSUE THREAD

**Issue by nshmyrev** [SpeechColab/GigaSpeech#62]
Is it possible to download dev/test set somehow instead of full set? Are they included in the data at all?

**Comment by chenguoguo** [comment]
That's a very good point, as we do want to use it for benchmarking as well. Unfortunately the current train/dev/test downloading processes are not separated. We can probably provide separate links for the dev/test sets. Will get back to this.

**Comment by dophist** [comment]
Hi Nickolay @nshmyrev ,
I prepared GigaSpeech EvaluationSets resources from IPFS, you can have a try to download:
1. download official IPFS downloader(ipget), I assume you have X86_64 linux server, you can get it here:
```
    https://dist.ipfs.io/ipget/v0.6.0/ipget_v0.6.0_linux-amd64.tar.gz
```
if you are downloading from Mac, you can find corresponding downloader distribution [here](https://dist.ipfs.io/#ipget)

2. Once you get the tool, you can try:
```
./ipget --progress  -o GigaSpeech  QmWH8qDBJbQa6s9okgMj42Dd2N8jFJyqbpyLHS9NPubEYN
```

It would be great if you can report on the downloading speed from your side to help us improve our GigaSpeech distribution channels.

**Comment by dophist** [comment]
Hi Nickolay @nshmyrev ,
I prepared GigaSpeech EvaluationSets resources from IPFS, you can have a try to download:

download official IPFS downloader(ipget), I assume you have X86_64 linux server, you can get it here:
```
    https://dist.ipfs.io/ipget/v0.6.0/ipget_v0.6.0_linux-amd64.tar.gz
```
if you are downloading from Mac, you can find corresponding downloader distribution here

Once you get the tool, you can try:
```
./ipget --progress  -o GigaSpeech  QmewVRGhxLXGUBD5QFmpPR2jnLbCjuNUcK5K9E4UzfaYaA
```
It would be great if you can report on the downloading speed from your side to help us improve our GigaSpeech distribution channels.

**Comment by dophist** [comment]
Hi Nickolay @nshmyrev ,
I prepared GigaSpeech EvaluationSets resources from IPFS, you can have a try to download:

1. download official IPFS downloader(ipget), I assume you have X86_64 linux server, you can get it here:
```
https://dist.ipfs.io/ipget/v0.6.0/ipget_v0.6.0_linux-amd64.tar.gz
```
if you are downloading from Mac, you can find corresponding downloader distribution [here](https://dist.ipfs.io/#ipget)

2. Once you get the tool, you can try:
```
./ipget --progress  -o GigaSpeech  QmewVRGhxLXGUBD5QFmpPR2jnLbCjuNUcK5K9E4UzfaYaA
```
It would be great if you can report on the downloading speed from your side to help us improve our GigaSpeech distribution channels.

The content address `QmewVRGhxLXGUBD5QFmpPR2jnLbCjuNUcK5K9E4UzfaYaA` might change in the future, I may keep it unchanged in the next couple of days I think.

**Comment by dophist** [comment]
IPFS pinning on my PC is not quite stable behind NAT, so the above downloading is not quite stable

**Comment by dophist** [comment]
This thread is kind of outdated, so I'm closing this.  Eval-set-only downloading is a reasonable feature, we may add this to our download tool as an enhancement later.
