### ISSUE TITLE
The speed for dataset downloading is very slow

### ISSUE THREAD

**Issue by dqqcasia** [SpeechColab/GigaSpeech#63]
> 0K .......... .......... .......... .......... ..........  0% 15.9K 4d13h
    50K .......... .......... .......... .......... ..........  0% 19.8K 4d3h
   100K .......... .......... .......... .......... ..........  0% 31.0K 3d12h
   150K .......... .......... .......... .......... ..........  0%  113K 2d19h
   200K .......... .......... .......... .......... ..........  0% 34.3K 2d16h
   250K .......... .......... .......... .......... ..........  0% 27.1K 2d16h
   300K .......... .......... .......... .......... ..........  0% 37.9K 2d13h
   350K .......... .......... .......... .......... ..........  0% 68.8K 2d9h
   400K .......... .......... .......... .......... ..........  0% 41.1K 2d7h
   450K .......... .......... .......... .......... ..........  0% 25.5K 2d8h
   500K .......... .......... .......... .......... ..........  0% 51.2K 2d6h
   550K .......... .......... .......... .......... ..........  0% 38.2K 2d6h
   600K .......... .......... .......... .......... ..........  0% 54.0K 2d4h
   650K .......... .......... .......... .......... ..........  0% 37.7K 2d4h
   700K .......... .......... .......... .......... ..........  0% 7.77K 2d15h
   750K .......... .......... .......... .......... ..........  0% 93.2K 2d12h
   800K .......... .......... .......... .......... ..........  0% 23.0K 2d13h
   850K .......... .......... .......... .......... ..........  0% 60.5K 2d11h
   900K .......... .......... .......... .......... ..........  0% 14.9K 2d14h
   950K .......... .......... .......... .......... ..........  0% 44.1K 2d13h
  1000K .......... .......... .......... .......... ..........  0% 19.8K 2d15h
  1050K .......... .......... .......... .......... ..........  0% 25.9K 2d15h
  1100K .......... .......... .......... .......... ..........  0% 31.8K 2d14h
  1150K .......... .......... .......... .......... ..........  0% 18.1K 2d16h

**Comment by chenguoguo** [comment]
See here, we are working on that...

**Comment by chenguoguo** [comment]
Added one host, and another is on the way. If you re-run your download script, it should be able to figure out the best download host: https://github.com/SpeechColab/GigaSpeech/pull/71

**Comment by xiaoxiao26** [comment]
Hi, I tried out the new SpeechOcean host yesterday and found download speed to be much faster, reaching 1-2 MB/s. Midway through the download, however, the speed went back down to 20-30 KB/s, and has stayed there for the past half day. Any idea why this could be the case? 20-30 KB/s makes the download time increase from several days to many months. Thanks!

**Comment by chenguoguo** [comment]
I think it's because more people switched to the speechocean host; the script will automatically find the fastest host so if you run it again, it should find the faster host for you.

We will likely add one more host this week.

**Comment by dophist** [comment]
refer to https://github.com/SpeechColab/GigaSpeech/issues/60 , all problems and solutions relating to GigaSpeech downloading are published to that issue tracker
