### ISSUE TITLE
Non-matching train subset sizes

### ISSUE THREAD

**Issue by pzelasko** [SpeechColab/GigaSpeech#65]
Using the Lhotse recipe, I am getting a significantly larger number of transcribed hours in XS, S and, M subsets than stated in this repo's README (10, 250, and 1000 hours respectively).

See:
![image](https://user-images.githubusercontent.com/15930688/125319549-deac2800-e308-11eb-828f-b09298d48085.png)

I don't think that Lhotse is doing anything fancy in that recipe -- it basically uses the `speechcolab` package to get a list of recordings for a given subset and reads what are the transcribed chunks (see: https://github.com/lhotse-speech/lhotse/blob/master/lhotse/recipes/gigaspeech.py#L84)

Note that I am showing the amount of _transcribed_ hours: e.g. for XS, the total recording duration is about 44 hours (out of which ~18h are transcribed).

**Comment by dophist** [comment]
Piotr, many thanks

I just wrote a script to parse supervision segments from GigaSpeech.json - v1.0.0 (numbers listed are in hours), here is what I got:
```
trn
{
    "{XL}": {
        "audiobook": 2653.3897499986906,
        "podcast": 3498.6537583320865,
        "youtube": 3845.780869441066
    },
    "{L}": {
        "audiobook": 650.0004888891012,
        "podcast": 874.8420527778551,
        "youtube": 975.0000333334893
    },
    "{M}": {
        "audiobook": 260.0012083333143,
        "podcast": 349.94648888888713,
        "youtube": 390.00038055555586
    },
    "{S}": {
        "audiobook": 65.00140833333303,
        "podcast": 87.48013611111121,
        "youtube": 97.50047500000021
    },
    "{XS}": {
        "audiobook": 2.603083333333337,
        "podcast": 3.500105555555565,
        "youtube": 3.9010277777777795
    }
}

```

@jimbozhang I noticed the numbers Piotr listed is somehow related to 1.6, is it some resampling and integer rounding stuff in PySpeechColab?
```
1599 / 1.6 ~= 999.375 hours (~= 1000 hours {M}
407 / 1.6 ~= 254.375 hours (~= 250 hours {S})
18 / 1.6 ~= 11.25 hours (~= 10 hours {XS})
```
Just a guess, can you help to have a look when you have time.

**Comment by pzelasko** [comment]
Hmm yeah, I'll take a second look at this and will let you know if I find out anything.

**Comment by pzelasko** [comment]
I am 99% certain this is something inside `speechcolab`; I am using the v1.0.0 GigaSpeech.json that you shared with me recently, and the following code reproduces my issue:

```python
>>> from speechcolab.datasets.gigaspeech import GigaSpeech
>>> g = GigaSpeech('/exp/pzelasko/gigaspeech/')
>>> tot = 0
>>> for x in g.audios('{XS}'):
...     for s in x['segments']:
...         tot += (s['end_time'] - s['begin_time'])
...
>>> tot
Decimal('65424.99')
>>> tot / 3600
Decimal('18.17360833333333333333333333')
```

**Comment by chenguoguo** [comment]
@jimbozhang could you take a look at PySpeechColab?

**Comment by pzelasko** [comment]
OK I understand now. After looking at the GigaSpeech JSON more closely I noticed that not every "segment" in a given recording belongs to the same subsets (i.e. some subsets of GigaSpeech use only a subset of segments in a given recording). I think it'd be good to modify the `.audios()` method in `speechcolab` to filter out the segments outside of the requested subset. I can make a PR.

**Comment by dophist** [comment]
> OK I understand now. After looking at the GigaSpeech JSON more closely I noticed that not every "segment" in a given recording belongs to the same subsets (i.e. some subsets of GigaSpeech use only a subset of segments in a given recording). I think it'd be good to modify the `.audios()` method in `speechcolab` to filter out the segments outside of the requested subset. I can make a PR.

Yeah, I see.  We used utterance-level granularity in subset selection so that small subsets can also have greater diversity.  And PySpeechColab code doesn't know this well enough, we'll fix it. Many thanks!

**Comment by chenguoguo** [comment]
I suppose the issue was resolved after https://github.com/SpeechColab/PySpeechColab/pull/6? Shall we close this?

**Comment by pzelasko** [comment]
Yes, it's solved. I'll close.
