### ISSUE TITLE
Download failed from Tsinghua University host

### ISSUE THREAD

**Issue by zhangguanqun** [SpeechColab/GigaSpeech#66]
--2021-07-14 12:26:24--  http://www.tsinghua-ieit.com/dataset/GigaSpeech/TERMS_OF_ACCESS
Resolving www.tsinghua-ieit.com (www.tsinghua-ieit.com)... 221.238.40.76
Connecting to www.tsinghua-ieit.com (www.tsinghua-ieit.com)|221.238.40.76|:80... connected.
HTTP request sent, awaiting response... Read error (Connection timed out) in headers.
Retrying.

--2021-07-14 12:41:25--  (try: 2)  http://www.tsinghua-ieit.com/dataset/GigaSpeech/TERMS_OF_ACCESS
Connecting to www.tsinghua-ieit.com (www.tsinghua-ieit.com)|221.238.40.76|:80... connected.
HTTP request sent, awaiting response... Read error (Connection timed out) in headers.
Retrying.

--2021-07-14 12:56:27--  (try: 3)  http://www.tsinghua-ieit.com/dataset/GigaSpeech/TERMS_OF_ACCESS
Connecting to www.tsinghua-ieit.com (www.tsinghua-ieit.com)|221.238.40.76|:80... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.

--2021-07-14 12:57:58--  (try: 4)  http://www.tsinghua-ieit.com/dataset/GigaSpeech/TERMS_OF_ACCESS
Connecting to www.tsinghua-ieit.com (www.tsinghua-ieit.com)|221.238.40.76|:80... connected.
HTTP request sent, awaiting response... Read error (Connection timed out) in headers.
Retrying.

--2021-07-14 13:13:02--  (try: 5)  http://www.tsinghua-ieit.com/dataset/GigaSpeech/TERMS_OF_ACCESS
Connecting to www.tsinghua-ieit.com (www.tsinghua-ieit.com)|221.238.40.76|:80... connected.
HTTP request sent, awaiting response... 

Time out all the time.

**Comment by chenguoguo** [comment]
It hit the maximum number of connections (unfortunately a lot of people are downloading it at the moment) and it was queued on the server. We've increased the maximum number of connections on the server so you should be able to download it now. It might be slow but we are in the process of adding more hosts.

**Comment by zhangguanqun** [comment]
Cool, it works now!
But with a very low speed around 10KB/s ;(

Guoguo Chen ***@***.***> 于2021年7月14日周三 下午3:54写道：

**Comment by chenguoguo** [comment]
Yeah it's slow for now... We are adding more hosts so things will improve. Let me close this ticket for now since it's working now.
