### ISSUE TITLE
测试结果

### ISSUE THREAD

**Issue by 7zhanghao** [SpeechColab/GigaSpeech#69]
你好这里给出的espnet上dev/test的wer为10.9/10.8左右，但是在espnet/egs2/gigaspeech/asr1里给出的结果是9.2/15.6，哪个是准确的？

**Comment by dophist** [comment]
> 你好这里给出的espnet上dev/test的wer为10.9/10.8左右，但是在espnet/egs2/gigaspeech/asr1里给出的结果是9.2/15.6，哪个是准确的？

Those numbers are based on an out-dated version of GigaSpeech evaluation sets.  We'll send updated numbers(which are currently listed in GigaSpeech Readme.md) to Espnet repo in a couple of weeks.

**Comment by chenguoguo** [comment]
Closing this since it has been explained.
