### ISSUE TITLE
missing `donwload.sh`

### ISSUE THREAD

**Issue by sw005320** [SpeechColab/GigaSpeech#7]
Where can we find `download.sh` written in https://github.com/SpeechColab/GigaSpeech#steps?
Or should we just run the following command shown in https://github.com/SpeechColab/GigaSpeech/blob/main/toolkits/kaldi/run_gigaspeech.sh#L16-L28?
```
utils/setup_oss_for_downloading.sh
utils/download_meta.sh
utils/download_audio.sh
```

**Comment by sw005320** [comment]
When I executed `utils/download_meta.sh`, I encountered the following error:

```
$ utils/download_meta.sh
Error: copy files between local file system is not allowed in ossutil, if you want to upload to oss, please make sure dest_url starts with "oss://",dest_url:/GigaSpeech.json
```

I followed https://github.com/SpeechColab/GigaSpeech#steps, but probably I misunderstood some instructions.
It would be great if you give me some suggestions of how to fix it.

**Comment by chenguoguo** [comment]
Ah sorry we forgot to update the README. I'll update it.

For now you can use the following script:
```bash
#!/usr/bin/env bash

. ./env_vars.sh

sh utils/setup_oss_for_downloading.sh

sh utils/download_meta.sh

# this currently download entire dataset, we may improve to support subset downloading
sh utils/download_audio.sh
```

Or you can also look into the first few stages of `toolkits/kaldi/run_gigaspeech.sh`

Let me know if you still have issues!

**Comment by sw005320** [comment]
Many thanks!
Now it's working
```
$ utils/download_meta.sh
Total num: 1, size: 3,766,838,768. Dealed num: 0, OK size: 47,085,485, Progress: 1.250%, Speed: 8824.22KB/s
```

**Comment by chenguoguo** [comment]
Great!
