### ISSUE TITLE
404 not found

### ISSUE THREAD

**Issue by mahuichao** [SpeechColab/GigaSpeech#73]
my connection is not stable,so when there is a disconnecting,  I restart it ,now I download 56 packages ,according to the json, I think total packags is 216。 Today when I restart it, there is a error:

> ./utils/download_gigaspeech.sh: Downloading from the Tsinghua University host...
utils/internal/download_gigaspeech_from_tsinghua.sh: Start to download GigaSpeech user agreement
--2021-07-20 10:18:48--  http://www.tsinghua-ieit.com/dataset/GigaSpeech/TERMS_OF_ACCESS
Resolving www.tsinghua-ieit.com (www.tsinghua-ieit.com)... 221.238.40.76
Connecting to www.tsinghua-ieit.com (www.tsinghua-ieit.com)|221.238.40.76|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-07-20 10:18:48 ERROR 404: Not Found.

I don't know what's wrong ,does access term have time limits? like a month ?  thanks in advance.

**Comment by double22a** [comment]
the same wrong, waiting for answer

**Comment by dophist** [comment]
Tsinghua server is under maintenance because somebody used multi-thread downloader which generates too many requests,  please try to resume downloading in 3-4 hours or so.

**Comment by chenguoguo** [comment]
The script was supposed to handle that since we have multiple hosts now. I have fixed the bug here: https://github.com/SpeechColab/GigaSpeech/pull/74

I'll merge after testing.

**Comment by chenguoguo** [comment]
If you run that script again, it should be able to download again from the speechocean host, from where it broke.

**Comment by mahuichao** [comment]
@dophist @chenguoguo  Thanks guys!
