### ISSUE TITLE
speechocean host login incorrect

### ISSUE THREAD

**Issue by todtom** [SpeechColab/GigaSpeech#75]
Run the download script, it choose speechocean host, but it report the "login incorrect" error and exit.

```utils/download_gigaspeech.sh: Testing Tsinghua host speed...
--2021-07-20 16:44:02--  http://www.tsinghua-ieit.com/dataset/GigaSpeech/GigaSpeech.json.gz.aes
Resolving www.tsinghua-ieit.com (www.tsinghua-ieit.com)... 221.238.40.76
Connecting to www.tsinghua-ieit.com (www.tsinghua-ieit.com)|221.238.40.76|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-07-20 16:44:03 ERROR 404: Not Found.


utils/download_gigaspeech.sh: The Tsinghua host speed: 0 M/s.

utils/download_gigaspeech.sh: Testing speechocean host speed...
--2021-07-20 16:44:03--  ftp://124.207.81.184/GigaSpeech/GigaSpeech.json.gz.aes
           => ‘/tmp/GigaSpeech.json.gz.aes’
Connecting to 124.207.81.184:21... connected.
Logging in as GigaSpeech ...
Login incorrect.```

**Comment by chenguoguo** [comment]
Did you apply for the credentials? See here: https://github.com/SpeechColab/GigaSpeech#download 

The speechocean host had some issues, but if you have the correct credentials under SAFEBOX/password from the application, it should at least be able to log in...

**Comment by todtom** [comment]
I have fill the google form and echo the password to the file SAFEBOX/password. Before the tsinghua host hang, I had successfully download hundreds file, after switch to the speechocean host, it report  login incorrect

**Comment by chenguoguo** [comment]
Could you do "git pull" and then try again?

**Comment by todtom** [comment]
I pull the repository again. The tsinghua host worked, the speechocean host still login incorrect.

**Comment by todtom** [comment]
Anyway there is one host worked, close the issue
