### ISSUE TITLE
Properly unzipping and checking the content of AES files (and downloading speed).

### ISSUE THREAD

**Issue by underdogliu** [SpeechColab/GigaSpeech#79]
Hey and thanks for such great dataset! So after getting the agreement and way to download, I am now downloading the data from Gigaspeech (with a low speed...I don't know, it may take weeks).

Meanwhile I fetched one partition but then found it with suffix `aes` (e.g. `P0000.tgz.aes`) and seems like I couldn't open it with macOS default archiver. Is it like its name indicates, AES-encrypted? If so, do we have instruction to open it properly so I can listen to some wave files?

P.S. Have we been working on the alternative way of downloading it or because of the bandwidth the speed cannot be optimized at this point?

**Comment by dophist** [comment]
You need credential to unzip (follow instructions in application verification email)

**Comment by underdogliu** [comment]
That is the problem - I did not find unzipping instructions in either verification emails or by reading the bash scripts.

**Comment by underdogliu** [comment]
Thanks @dophist and @chenguoguo I found the unzipping command in `utils/internal/download_gigaspeech_from_tsinghua.sh`. But I may suggest that we discuss a bit at README or at least give a pointer on how to check the wave files.

Besides, it seems like the openssl command in the bash file can't be replicated under macOS. I am not sure if that is an issue - maybe it's not because servers are mostly (if not all) hosted with linux LTS OS.

**Comment by dophist** [comment]
> Thanks @dophist and @chenguoguo I found the unzipping command in `utils/internal/download_gigaspeech_from_tsinghua.sh`. But I may suggest that we discuss a bit at README or at least give a pointer on how to unzip the wave files.
> 
> Besides, it seems like the openssl command in the bash file can't be replicated under macOS. I am not sure if that is an issue - maybe it's not because servers are mostly (if not all) hosted with linux LTS OS.

I really don't suggest that you handle decryption&decompress stuff yourself. By doing so, you are actually escaping the "happy-path" of dataset distribution tools(tested by us), for what. The downloading is slow indeed, it's not a problem of codes, it's about resources.  If anyone can provide 100G bandwidth network and hosting for free, all problems are gone.

**Comment by underdogliu** [comment]
No I am not creating any separate script or something 😂 what I am saying is if somebody, for example, during downloading, wanna listen to some wave files to have a gist, at least we can say something like "If you would like to listen to some waves by yourself, please check `utils/internal/download_gigaspeech_from_tsinghua.sh` for details."

Alternatively, if we would like to not be bothered with such process, we can provide some samples from each partition - several waves for each would suffice, for who are interested.

**Comment by dophist** [comment]
Noted.  This is not in our near plan.  For now, stable dataset distribution is first priority.  Feel free to close the issue.
