### ISSUE TITLE
About "Broken pipe" in the json pipeline

### ISSUE THREAD

**Issue by underdogliu** [SpeechColab/GigaSpeech#83]
First of all thanks for new host of GigaSpeech! Downloading has been much faster than before.

One problem comes to the extracting script. In `utils/extract_metadata_version.sh`, I found there is a printing command
```
if [ -f $gigaspeech_dataset_dir/GigaSpeech.json ]; then
  cat $gigaspeech_dataset_dir/GigaSpeech.json | jq -r '.version'
else
  >&2 echo "$0: ERROR, couldn't find $gigaspeech_dataset_dir/GigaSpeech.json"
  exit 1
fi
```
where I speculated the cat command will fail due to the large pipe size of the json file. And it returns as speculated - process got killed on a 8GB memory server. I believe it's because my server is weak but I wonder if we have more advanced json-grepping method or we need one?

**Comment by dophist** [comment]
It is assumed that your machine should have big enough memory to parse GigaSpeech.json.  If it is impossible for you to find a proper machine, I guess you can try `head GigaSpeech.json` manually and `echo` the version number to get rid of those json-parsing stuff.
