### ISSUE TITLE
Can you add option to skip check files  have been downloaded? 

### ISSUE THREAD

**Issue by al3chen** [SpeechColab/GigaSpeech#91]
Can you add option to skip check files  have been downloaded? 

====================================================================
Start to download files.yaml
Start to download GigaSpeech metadata
Skipping /home/dev/bigvdata/GigaSpeech.json.gz.aes, successfully retrieved already.
Skipping /home/dev/bigvdata/audio/youtube/P0001.tgz.aes, successfully retrieved already.
Skipping /home/dev/bigvdata/audio/youtube/P0002.tgz.aes, successfully retrieved already.
Skipping /home/dev/bigvdata/audio/youtube/P0003.tgz.aes, successfully retrieved already.
Skipping /home/dev/bigvdata/audio/youtube/P0004.tgz.aes, successfully retrieved already.
Skipping /home/dev/bigvdata/audio/youtube/P0005.tgz.aes, successfully retrieved already.
Skipping /home/dev/bigvdata/audio/youtube/P0006.tgz.aes, successfully retrieved already.
Skipping /home/dev/bigvdata/audio/youtube/P0007.tgz.aes, successfully retrieved already.
Skipping /home/dev/bigvdata/audio/youtube/P0008.tgz.aes, successfully retrieved already.
Skipping /home/dev/bigvdata/audio/youtube/P0009.tgz.aes, successfully retrieved already.

**Comment by dophist** [comment]
Tuthless checking for data correctness is essential for data set downloading, especially for large corpus like GigaSpeech.  It may be painful to wait, but it's way much better than dealing with issues relating to data corruption & incomplete downloads later.
